### ISSUE TITLE
ImageNet pretrained weight

### ISSUE THREAD

**Issue by lh-zhu** [johnnylu305/deeplab-imagenet-pytorch#1]
Greetings,

I have a great interest in your work! Could you please share your ImageNet pretrained weight to me? Thanks!

**Comment by johnnylu305** [comment]
If I remember correctly, the code will automatically download the ImageNet pretrain weight. The pretrain weight that I used came from the official Pytorch.

**Comment by johnnylu305** [comment]
Please refer https://pytorch.org/vision/stable/models.html for more details. Hope this can help you.

**Comment by lh-zhu** [comment]
Yes, thanks, when I read your code, I found your pre-trained model loaded part, thanks you!
